// @flow
export const LIST_FILTERS_STATE_SELECT: 'LIST_FILTERS_STATE_SELECT' = 'LIST_FILTERS_STATE_SELECT';
export const LIST_FILTERS_CITY_SELECT: 'LIST_FILTERS_CITY_SELECT' = 'LIST_FILTERS_CITY_SELECT';
export const LIST_FILTERS_NAME_SELECT: 'LIST_FILTERS_NAME_SELECT' = 'LIST_FILTERS_NAME_SELECT';
export const LIST_FILTERS_TYPE_SELECT: 'LIST_FILTERS_TYPE_SELECT' = 'LIST_FILTERS_TYPE_SELECT';
export const LIST_FILTERS_TAGS_SELECT: 'LIST_FILTERS_TAGS_SELECT' = 'LIST_FILTERS_TAGS_SELECT';
export const LIST_FILTERS_KEYWORD_SELECT: 'LIST_FILTERS_KEYWORD_SELECT' = 'LIST_FILTERS_KEYWORD_SELECT';
export const LIST_FILTERS_PAGE_SELECT: 'LIST_FILTERS_PAGE_SELECT' = 'LIST_FILTERS_PAGE_SELECT';
export const LIST_FILTERS_PAGE_SIZE_SELECT: 'LIST_FILTERS_PAGE_SIZE_SELECT' = 'LIST_FILTERS_PAGE_SIZE_SELECT';

export const LIST_GET_REQUEST: 'LIST_GET_REQUEST' = 'LIST_GET_REQUEST';
export const LIST_GET_FAILURE: 'LIST_GET_FAILURE' = 'LIST_GET_FAILURE';
export const LIST_GET_SUCCESS: 'LIST_GET_SUCCESS' = 'LIST_GET_SUCCESS';

export const LIST_SEARCH_GET_REQUEST: 'LIST_SEARCH_GET_REQUEST' = 'LIST_SEARCH_GET_REQUEST';
export const LIST_SEARCH_GET_FAILURE: 'LIST_SEARCH_GET_FAILURE' = 'LIST_SEARCH_GET_FAILURE';
export const LIST_SEARCH_GET_SUCCESS: 'LIST_SEARCH_GET_SUCCESS' = 'LIST_SEARCH_GET_SUCCESS';

export const LIST_SORT: 'LIST_SORT' = 'LIST_SORT';

export const LIST_CLEAR_ALL_FILTERS: 'LIST_CLEAR_ALL_FILTERS' = 'LIST_CLEAR_ALL_FILTERS';

export const ITEM_GET_REQUEST: 'ITEM_GET_REQUEST' = 'ITEM_GET_REQUEST';
export const ITEM_GET_FAILURE: 'ITEM_GET_FAILURE' = 'ITEM_GET_FAILURE';
export const ITEM_GET_SUCCESS: 'ITEM_GET_SUCCESS' = 'ITEM_GET_SUCCESS';
export const ITEM_SELECT_ID: 'ITEM_SELECT_ID' = 'ITEM_SELECT_ID';
